### ISSUE TITLE
Fix/ Get Pytest working in the project

### ISSUE THREAD

**Issue by DanielNWilsher** [songchanyeah/cs2450#50]
fix this issue for pytest.

=========================================================================== ERRORS ===========================================================================
_________________________________________________________ ERROR collecting Test Files/test_sample.py _________________________________________________________
ImportError while importing test module '/Users/danielwilsher/Desktop/cs2450/Test Files/test_sample.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Test Files/test_sample.py:1: in <module>
    from myClasses.UVSim_Class import UVSim
E   ModuleNotFoundError: No module named 'myClasses'

**Comment by DanielNWilsher** [comment]
We want to get it looking back like this

![Image](https://github.com/songchanyeah/cs2450/assets/68828167/c19bf8c1-5b9f-4896-bc50-c1f4b37eb4b2)

**Comment by songchanyeah** [comment]
When running pytest, use "python -m pytest -s"

**Comment by songchanyeah** [comment]
Also, fixed filepath on this branch.
